#!/bin/bash

echo "GitHub Push Helper for learning.chrispeterkins.com"
echo "===================================================="
echo ""
echo "This repository is ready to push to: https://github.com/ChrisPeterkins/learning.chrispeterkins.com"
echo ""
echo "Choose your authentication method:"
echo ""
echo "Option 1: GitHub Personal Access Token (Recommended)"
echo "-----------------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Create a token with 'repo' scope"
echo "3. Run: git push https://YOUR_TOKEN@github.com/ChrisPeterkins/learning.chrispeterkins.com.git main"
echo ""
echo "Option 2: GitHub CLI Authentication"
echo "------------------------------------"
echo "Run these commands:"
echo "  gh auth login"
echo "  gh auth setup-git"
echo "  git push -u origin main"
echo ""
echo "Option 3: SSH Key Setup"
echo "------------------------"
echo "1. Generate SSH key: ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "2. Add key to GitHub: https://github.com/settings/keys"
echo "3. Change remote to SSH: git remote set-url origin git@github.com:ChrisPeterkins/learning.chrispeterkins.com.git"
echo "4. Push: git push -u origin main"
echo ""
echo "Current status:"
git status --short
echo ""
echo "Last commit:"
git log --oneline -1
echo ""
echo "Remote configured:"
git remote -v